modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="gxr"
version="1.0.0"
displayName="GXR"
displayURL="https://gxr806.site"
credits="技术支持：Mcreator"
authors="郭笑然"
description="这个模组添加了一些脑洞大开的简单东西"

[[dependencies.gxr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




